import type {Metadata} from "next";
import "../assets/styles/globals.css";
import style from "./Layout.module.scss"
import {inter} from "../assets/fonts/fonts";
import {clsx} from "clsx";
import {StoreProvider} from "../store/StoreProvider";
import {Header} from "../components/A0_Header/Header";

export const metadata: Metadata = {
    title: "Meta Funding",
    //description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={clsx(style.layout, inter.className)}>

        <StoreProvider>
            <>
                <Header/>

                <main>
                    {children}
                </main>
            </>
        </StoreProvider>


        </body>
        </html>
    );
}
